#566 Fixed stack trace when exporting a workflow
If a Workflow had a node whose job template was removed from under it you would get a stack trace. This commit fixes that issue. Now, a message will be displayed:

tower-cli receive --tower-host http://localhost:8081 --workflow "Deleted Node Template"

Error: Workflow export exception: workflow Deleted Node Template has a node whose job template has been deleted